### ISSUE TITLE
Binja installation path detector does not work with Python 3.11

### ISSUE THREAD

**Issue by xusheng6** [mandiant/capa#1430]
Just tried the fresh 5.1.0 release, and notice it does not work if the system Python version is 3.11. The problem is with the binja installation path detector. The offending line is https://github.com/mandiant/capa/blob/master/capa/features/extractors/binja/find_binja_api.py#L18-L19. 

In Python 3.11, the importlib module seems to have changed, and we cannot access `importlib.util` in the old way:

```
>>> import importlib
>>> importlib.util
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'importlib' has no attribute 'util'
```

Simply changing it to sth like this would work:

```
>>> import importlib.util
>>> importlib.util.find_spec('binaryninja')
```

**Comment by xusheng6** [comment]
Except this case it works for me!

**Comment by xusheng6** [comment]
I will submit a PR for this later

**Comment by williballenthin** [comment]
hm, how come our CI tests didn't catch this?

**Comment by williballenthin** [comment]
ah, because this code path is only encountered in standalone mode:
